parameters:
#    acme_sniffer.example.class: Acme\SnifferBundle\Example

services:
#    acme_sniffer.example:
#        class: %acme_sniffer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
